Replace npm release yml with release yml [sc-19228]

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,8 +10,9 @@ on:
         required: true
         default: 'dev'
         type: choice
-        options: 
+        options:
           - dev
+          - ic
       release_npm:
         description: 'Run the NPM package release part'
         required: true
@@ -20,6 +21,13 @@ on:
         options: 
           - false
           - true
+      deploy_playground:
+        description: 'Deploy playground and canisters'
+        default: 'true'
+        type: choice
+        options:
+          - true
+          - false
       force_deploy:
         description: 'Force deploy'
         default: 'false'
@@ -46,8 +54,15 @@ jobs:
     permissions:
       contents: read
       id-token: write
+      packages: write
 
     steps:
+      - name: INPUT => Checks npm publishing confirmation
+        if: ${{ env.NETWORK_NAME == 'ic' && github.event_name == 'workflow_dispatch' && github.event.inputs.confirmation != 'Yes' }}
+        run: |
+          echo "[ERROR] You have tried to publish to npm without or with wrong confirmation phrase" >&2
+          exit 1
+
       - name: Checkout repo
         uses: actions/checkout@v6
 
@@ -128,7 +143,7 @@ jobs:
       - name: Publish
         working-directory: packages/identitykit
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
+          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
         run: |
           source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
@@ -150,7 +165,7 @@ jobs:
   playground-deploy:
     name: Build and Deploy Playground
     # needs: npm-publish
-    if: ${{ (github.event_name != 'release' && (!failure() || !cancelled())) || (github.event_name == 'release' && success()) }}
+    if: ${{ github.event.inputs.deploy_playground != 'false' && ((github.event_name != 'release' && (!failure() || !cancelled())) || (github.event_name == 'release' && success())) }}
     environment: ${{ github.event.inputs.network_name || ( contains(github.event_name, 'release') && 'ic' || 'dev' ) }}
     runs-on: ubuntu-latest
     defaults:
